### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by zub0r** [jimmywarting/not-a-log#1]
Hi, thanks for this helper, however when I try to use it in node, it fails to compile the module. Any suggesions?

```
[INFO] 12:35:02 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.6.4)
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/not-a-log/not-a-log.js from src/main.ts not supported.
Instead change the require of not-a-log.js in src/main.ts to a dynamic import() which is available in all CommonJS modules.
```

**Comment by jimmywarting** [comment]
Like the error explains... this is a ESM only modules, and the only way you can import it is with `import` syntax that don't compile down to `require()` syntax durning your build step.

you can either change your target output to be in ESM as well and add type=module in package json
or you will have to import "not-a-log" using async import that is also avalible from commonjs using `import('not-a-log').then(module => { ... })`

there is a better guide here: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by zub0r** [comment]
Thanks for the clarification!
